package project;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.regex.Pattern;


public class foodcourt extends javax.swing.JFrame {

    /**
     * Creates new form foodcourt
     */
    public foodcourt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading1 = new javax.swing.JLabel();
        heading2 = new javax.swing.JLabel();
        heading3 = new javax.swing.JLabel();
        heading4 = new javax.swing.JLabel();
        harga_menu1 = new javax.swing.JLabel();
        harga_menu2 = new javax.swing.JLabel();
        harga_menu3 = new javax.swing.JLabel();
        harga_menu4 = new javax.swing.JLabel();
        sum_menu1 = new javax.swing.JTextField();
        sum_menu2 = new javax.swing.JTextField();
        sum_menu3 = new javax.swing.JTextField();
        sum_menu4 = new javax.swing.JTextField();
        harga_menu5 = new javax.swing.JLabel();
        harga_menu6 = new javax.swing.JLabel();
        harga_menu7 = new javax.swing.JLabel();
        harga_menu8 = new javax.swing.JLabel();
        sum_menu5 = new javax.swing.JTextField();
        sum_menu6 = new javax.swing.JTextField();
        sum_menu7 = new javax.swing.JTextField();
        sum_menu8 = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        btnCount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total_harga = new javax.swing.JTextField();
        field_pembayaran = new javax.swing.JTextField();
        field_kembalian = new javax.swing.JTextField();
        qty_menu1 = new javax.swing.JTextField();
        qty_menu2 = new javax.swing.JTextField();
        qty_menu3 = new javax.swing.JTextField();
        qty_menu4 = new javax.swing.JTextField();
        menu1 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        menu3 = new javax.swing.JLabel();
        menu4 = new javax.swing.JLabel();
        qty_menu5 = new javax.swing.JTextField();
        menu5 = new javax.swing.JLabel();
        qty_menu6 = new javax.swing.JTextField();
        menu6 = new javax.swing.JLabel();
        qty_menu7 = new javax.swing.JTextField();
        menu7 = new javax.swing.JLabel();
        qty_menu8 = new javax.swing.JTextField();
        menu8 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        heading1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        heading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading1.setText("HAFIDZ FOOD COURT");

        heading2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        heading2.setText("DAFTAR MENU");

        heading3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        heading3.setText("Minuman");

        heading4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        heading4.setText("Makanan");

        harga_menu1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu1.setText("Rp. 15.000,-");

        harga_menu2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu2.setText("Rp. 12.000,-");

        harga_menu3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu3.setText("Rp. 18.000,-");

        harga_menu4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu4.setText("Rp. 10.000,-");

        sum_menu1.setEditable(false);
        sum_menu1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        sum_menu2.setEditable(false);
        sum_menu2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        sum_menu3.setEditable(false);
        sum_menu3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        sum_menu4.setEditable(false);
        sum_menu4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        harga_menu5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu5.setText("Rp. 3.000,-");

        harga_menu6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu6.setText("Rp. 4.000,-");

        harga_menu7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu7.setText("Rp. 6.000,-");

        harga_menu8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        harga_menu8.setText("Rp. 9.000,-");

        sum_menu5.setEditable(false);
        sum_menu5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        sum_menu6.setEditable(false);
        sum_menu6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        sum_menu7.setEditable(false);
        sum_menu7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        sum_menu8.setEditable(false);
        sum_menu8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        btnCek.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        btnCount.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        btnCount.setText("Hitung");
        btnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Jumlah Yang Harus Dibayar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("Jumlah Pembayaran");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setText("Jumlah Kembalian");

        total_harga.setEditable(false);
        total_harga.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        total_harga.setText("0");

        field_pembayaran.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_pembayaran.setForeground(new java.awt.Color(153, 153, 153));
        field_pembayaran.setText("Inputkan uang anda");
        field_pembayaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_pembayaranFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_pembayaranFocusLost(evt);
            }
        });
        field_pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_pembayaranKeyReleased(evt);
            }
        });

        field_kembalian.setEditable(false);
        field_kembalian.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_kembalian.setText("0");

        qty_menu1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu1KeyReleased(evt);
            }
        });

        qty_menu2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu2KeyReleased(evt);
            }
        });

        qty_menu3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu3KeyReleased(evt);
            }
        });

        qty_menu4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu4KeyReleased(evt);
            }
        });

        menu1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu1.setText("Nasi Goreng");

        menu2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu2.setText("Mie Goreng");

        menu3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu3.setText("Cap Jay");

        menu4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu4.setText("Bihun Goreng");

        qty_menu5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu5KeyReleased(evt);
            }
        });

        menu5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu5.setText("Es Teh");

        qty_menu6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu6KeyReleased(evt);
            }
        });

        menu6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu6.setText("Es Jeruk");

        qty_menu7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu7KeyReleased(evt);
            }
        });

        menu7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu7.setText("Kelapa Muda");

        qty_menu8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        qty_menu8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qty_menu8KeyReleased(evt);
            }
        });

        menu8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        menu8.setText("Soda Gembira");

        error.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heading2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCek)
                                    .addComponent(btnCount))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(336, 336, 336)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(qty_menu6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(menu6))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(qty_menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(menu5))
                                                    .addComponent(heading3)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(qty_menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(qty_menu8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(menu8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(field_kembalian, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(total_harga, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(field_pembayaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(harga_menu8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(harga_menu5)
                                                        .addComponent(harga_menu7, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(harga_menu6))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sum_menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sum_menu6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sum_menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sum_menu8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(heading4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qty_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qty_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qty_menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qty_menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menu1)
                                    .addComponent(menu2)
                                    .addComponent(menu3)
                                    .addComponent(menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(harga_menu3)
                                    .addComponent(harga_menu2)
                                    .addComponent(harga_menu1)
                                    .addComponent(harga_menu4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sum_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sum_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sum_menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sum_menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(heading1))))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(heading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heading2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(heading4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qty_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qty_menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(menu5)
                                .addComponent(harga_menu5)
                                .addComponent(sum_menu5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sum_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu2)
                            .addComponent(harga_menu2)
                            .addComponent(qty_menu6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu6)
                            .addComponent(harga_menu6)
                            .addComponent(sum_menu6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sum_menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty_menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu3)
                            .addComponent(harga_menu3)
                            .addComponent(qty_menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu7)
                            .addComponent(harga_menu7)
                            .addComponent(sum_menu7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sum_menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty_menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu4)
                            .addComponent(harga_menu4)
                            .addComponent(qty_menu8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menu8)
                            .addComponent(harga_menu8)
                            .addComponent(sum_menu8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga_menu1)
                            .addComponent(menu1)
                            .addComponent(sum_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(error)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCek)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCount)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private Integer changePriceFormat(String price) {
       String[] arrPrice = price.split(" ", 5);
       String newPrice = arrPrice[1].replace(",-","");
       newPrice = newPrice.replace(".","");
       
       return Integer.parseInt(newPrice);
    }
    
    private String toRupiah(String price) {
       int newPrice = Integer.parseInt(price); 
       NumberFormat nf = NumberFormat.getNumberInstance(new Locale("in", "ID"));
       
       return nf.format(newPrice);
    }
    
    private String toRupiahWithRP(String price) {
        int newPrice = Integer.parseInt(price);
        Locale localeID = new Locale("in", "ID");
        NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);
        return formatRupiah.format(newPrice);
    }
    
    private boolean isInteger(String text) {
       return Pattern.matches("\\d*", text);
    }
    
    private String deleteDot(String text) {
        if(text.contains(".")){
            text = text.replace(".", "");
        }
        
        return text;
    }
    
    private void qty_menu1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu1KeyReleased
        if(!qty_menu1.getText().isEmpty() && this.isInteger(qty_menu1.getText())){
            int harga1 = this.changePriceFormat(harga_menu1.getText());
            String qty = qty_menu1.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu1.setText(result);
        } else {
            sum_menu1.setText("");
        }
    }//GEN-LAST:event_qty_menu1KeyReleased

    private void qty_menu2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu2KeyReleased
        if(!qty_menu2.getText().isEmpty() && this.isInteger(qty_menu2.getText())){
            int harga1 = this.changePriceFormat(harga_menu2.getText());
            String qty = qty_menu2.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu2.setText(result);
        } else {
            sum_menu2.setText("");
        }
    }//GEN-LAST:event_qty_menu2KeyReleased

    private void qty_menu3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu3KeyReleased
        if(!qty_menu3.getText().isEmpty() && this.isInteger(qty_menu3.getText())){
            int harga1 = this.changePriceFormat(harga_menu3.getText());
            String qty = qty_menu3.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu3.setText(result);
        } else {
            sum_menu3.setText("");
        }
    }//GEN-LAST:event_qty_menu3KeyReleased

    private void qty_menu4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu4KeyReleased
        if(!qty_menu4.getText().isEmpty() && this.isInteger(qty_menu4.getText())){
            int harga1 = this.changePriceFormat(harga_menu4.getText());
            String qty = qty_menu4.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu4.setText(result);
        } else {
            sum_menu4.setText("");
        }
    }//GEN-LAST:event_qty_menu4KeyReleased

    private void qty_menu5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu5KeyReleased
        if(!qty_menu5.getText().isEmpty() && this.isInteger(qty_menu5.getText())){
            int harga1 = this.changePriceFormat(harga_menu5.getText());
            String qty = qty_menu5.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu5.setText(result);
        } else {
            sum_menu5.setText("");
        }
    }//GEN-LAST:event_qty_menu5KeyReleased

    private void qty_menu6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu6KeyReleased
        if(!qty_menu6.getText().isEmpty() && this.isInteger(qty_menu6.getText())){
            int harga1 = this.changePriceFormat(harga_menu6.getText());
            String qty = qty_menu6.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu6.setText(result);
        } else {
            sum_menu6.setText("");
        }
    }//GEN-LAST:event_qty_menu6KeyReleased

    private void qty_menu7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu7KeyReleased
        if(!qty_menu7.getText().isEmpty() && this.isInteger(qty_menu7.getText())){
            int harga1 = this.changePriceFormat(harga_menu7.getText());
            String qty = qty_menu7.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu7.setText(result);
        } else {
            sum_menu7.setText("");
        }
    }//GEN-LAST:event_qty_menu7KeyReleased

    private void qty_menu8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_menu8KeyReleased
        if(!qty_menu8.getText().isEmpty() && this.isInteger(qty_menu8.getText())){
            int harga1 = this.changePriceFormat(harga_menu8.getText());
            String qty = qty_menu8.getText();
            int sum = Integer.parseInt(qty) * harga1;
            String result = this.toRupiah(Integer.toString(sum));
        
            sum_menu8.setText(result);
        } else {
            sum_menu8.setText("");
        }
    }//GEN-LAST:event_qty_menu8KeyReleased
    
    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
       String sumMenu1 = sum_menu1.getText();
       String sumMenu2 = sum_menu2.getText();
       String sumMenu3 = sum_menu3.getText();
       String sumMenu4 = sum_menu4.getText();
       String sumMenu5 = sum_menu5.getText();
       String sumMenu6 = sum_menu6.getText();
       String sumMenu7 = sum_menu7.getText();
       String sumMenu8 = sum_menu8.getText();
       
       String[] allSum = {sumMenu1,sumMenu2,sumMenu3,sumMenu4,sumMenu5,sumMenu6,sumMenu7,sumMenu8};
       int sumTmp = 0;
       
       for(String i : allSum) {
           if(!i.isEmpty()){
               i = this.deleteDot(i);
               sumTmp += Integer.parseInt(i);
           }
       }
       
       String total = Integer.toString(sumTmp);   
       if(!total.equals("0")) {
            total_harga.setText(this.toRupiahWithRP(Integer.toString(sumTmp)));
       } else {
            total_harga.setText(Integer.toString(sumTmp));
       }
    }//GEN-LAST:event_btnCekActionPerformed

    private void field_pembayaranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_pembayaranFocusGained
        if(field_pembayaran.getText().equals("Inputkan uang anda")){
            field_pembayaran.setText("");
            field_pembayaran.setForeground(Color.black);
        }
    }//GEN-LAST:event_field_pembayaranFocusGained

    private void field_pembayaranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_pembayaranFocusLost
        if(field_pembayaran.getText().equals("")){
            field_pembayaran.setText("Inputkan uang anda");
            field_pembayaran.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_field_pembayaranFocusLost

    private void field_pembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pembayaranKeyReleased
        String bayar = this.deleteDot(field_pembayaran.getText());
        if(!bayar.isEmpty() && this.isInteger(bayar)){
            field_pembayaran.setText(this.toRupiah(bayar));
        } else {
            field_pembayaran.setText("");
        }
    }//GEN-LAST:event_field_pembayaranKeyReleased

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
        String total = this.deleteDot(total_harga.getText().replace("Rp", ""));
        total = total.replace(",00", "");
        
        String uang = this.deleteDot(field_pembayaran.getText());
        if(Integer.parseInt(uang) >= Integer.parseInt(total)) {
            error.setText("");
            int kembalian = Integer.parseInt(uang) - Integer.parseInt(total);
            if(kembalian != 0){
                field_kembalian.setText(this.toRupiahWithRP(Integer.toString(kembalian)));
            } else {
                field_kembalian.setText("0");
            }
        } else {
            field_kembalian.setText("0");
            error.setText("Uang tidak cukup!");
        }
    }//GEN-LAST:event_btnCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodcourt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodcourt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodcourt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodcourt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodcourt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnCount;
    private javax.swing.JLabel error;
    private javax.swing.JTextField field_kembalian;
    private javax.swing.JTextField field_pembayaran;
    private javax.swing.JLabel harga_menu1;
    private javax.swing.JLabel harga_menu2;
    private javax.swing.JLabel harga_menu3;
    private javax.swing.JLabel harga_menu4;
    private javax.swing.JLabel harga_menu5;
    private javax.swing.JLabel harga_menu6;
    private javax.swing.JLabel harga_menu7;
    private javax.swing.JLabel harga_menu8;
    private javax.swing.JLabel heading1;
    private javax.swing.JLabel heading2;
    private javax.swing.JLabel heading3;
    private javax.swing.JLabel heading4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu2;
    private javax.swing.JLabel menu3;
    private javax.swing.JLabel menu4;
    private javax.swing.JLabel menu5;
    private javax.swing.JLabel menu6;
    private javax.swing.JLabel menu7;
    private javax.swing.JLabel menu8;
    private javax.swing.JTextField qty_menu1;
    private javax.swing.JTextField qty_menu2;
    private javax.swing.JTextField qty_menu3;
    private javax.swing.JTextField qty_menu4;
    private javax.swing.JTextField qty_menu5;
    private javax.swing.JTextField qty_menu6;
    private javax.swing.JTextField qty_menu7;
    private javax.swing.JTextField qty_menu8;
    private javax.swing.JTextField sum_menu1;
    private javax.swing.JTextField sum_menu2;
    private javax.swing.JTextField sum_menu3;
    private javax.swing.JTextField sum_menu4;
    private javax.swing.JTextField sum_menu5;
    private javax.swing.JTextField sum_menu6;
    private javax.swing.JTextField sum_menu7;
    private javax.swing.JTextField sum_menu8;
    private javax.swing.JTextField total_harga;
    // End of variables declaration//GEN-END:variables
}
